<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iIToggleMenuIcon</name>
   <tag></tag>
   <elementGuidId>0a02a34b-441a-4d36-bd87-4b1a19dc86ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#IToggleMenuIcon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='IToggleMenuIcon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>06a386e6-5d35-4985-895c-40228fbbf8a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>IToggleMenuIcon</value>
      <webElementGuid>a4ce8184-a47e-46f9-8447-f4071ba7d16b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material-icons md-22 Color_DarkYellow MenuButton</value>
      <webElementGuid>b2c4209b-a07e-4fc4-958e-22f184200b01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IToggleMenuIcon&quot;)</value>
      <webElementGuid>9fa89f94-14eb-4e6d-8bd0-63af6a6733cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='IToggleMenuIcon']</value>
      <webElementGuid>b07e3520-331c-4a15-9532-d1dbfb744c0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DivMenuToggleButton']/i</value>
      <webElementGuid>cba69c0a-2676-4a37-ac62-723fba12c331</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/i</value>
      <webElementGuid>0008e129-ac1f-4d39-a39d-38b260caafd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'IToggleMenuIcon']</value>
      <webElementGuid>bc6d916e-2da4-42cb-9228-ed8f522a4a52</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
