<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputmySearch</name>
   <tag></tag>
   <elementGuidId>bb58ead0-217a-49da-b0e4-763116665877</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mySearch</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mySearch']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3b26ae5f-b4d5-4234-9823-510b4ff81907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mySearch</value>
      <webElementGuid>a6202bcd-c998-4e68-bf90-3b4950db7874</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TxtWithNoBorder form-control-sidebar</value>
      <webElementGuid>01330c0e-d716-4b47-a93c-2542503ab1d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>c266f5a7-cc15-4695-ad37-de52fcf49c42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>search menu here...</value>
      <webElementGuid>604b3b36-dcc7-4686-a6de-bbcea69774ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>ecc4f142-50c1-4768-8a04-dcdaf85a9a7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mySearch&quot;)</value>
      <webElementGuid>800e7b75-f6f7-4a52-9e1a-2b60e9b28a47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mySearch']</value>
      <webElementGuid>92878dfe-d19c-4833-a2c4-6d50c989e03a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SearchMenu']/div/div/input</value>
      <webElementGuid>350d7e3d-2b61-44ce-bf58-1b56df0c15ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>f39ba3ac-db43-48ad-a3c0-b72bcff2bd19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'mySearch' and @type = 'search' and @placeholder = 'search menu here...']</value>
      <webElementGuid>912b5d32-ecbe-4de4-80b9-04d0615042a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
