<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>strong_Em</name>
   <tag></tag>
   <elementGuidId>aaec69a8-7c92-4915-949f-cb185b55a394</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='SearchMenu']/div/div[2]/div/a[5]/div[2]/strong</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>7191f606-8d58-4e2c-a444-fba169ddc579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-light</value>
      <webElementGuid>44b864f1-cf83-4705-a048-1553775e6f10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Em</value>
      <webElementGuid>2ae2c6a8-4e5c-4aa7-8c72-06eeacde2d53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SearchMenu&quot;)/div[@class=&quot;form-inline sidebar-search-open&quot;]/div[@class=&quot;sidebar-search-results&quot;]/div[@class=&quot;list-group&quot;]/a[@class=&quot;list-group-item&quot;]/div[@class=&quot;search-title&quot;]/strong[@class=&quot;text-light&quot;]</value>
      <webElementGuid>47e885a3-11e1-4f8c-b187-e6de84985574</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SearchMenu']/div/div[2]/div/a[5]/div[2]/strong</value>
      <webElementGuid>f837ab16-ed07-4764-941a-0459e32a7bd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[5]/div[2]/strong</value>
      <webElementGuid>e9edb3e4-9755-4e6c-a347-6130b04280cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[(text() = 'Em' or . = 'Em')]</value>
      <webElementGuid>27bc2079-1782-4a3f-a46e-8f3f5993419c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
