<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_add</name>
   <tag></tag>
   <elementGuidId>c2605c25-d578-4269-9587-e03bd3636c2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.material-icons.md-12.BgPoptiGreen.Color_White.Round_100.Hover</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='LnkAddItem']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>d8382665-1bb7-40fc-9d68-c747bf0b3a1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material-icons md-12 BgPoptiGreen Color_White Round_100 Hover</value>
      <webElementGuid>530bde5d-f92c-40b5-b58d-3ffa88db0818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>add</value>
      <webElementGuid>42a83fab-a38e-477c-9a95-70ff60819b9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LnkAddItem&quot;)/i[@class=&quot;material-icons md-12 BgPoptiGreen Color_White Round_100 Hover&quot;]</value>
      <webElementGuid>af165fec-4c27-49a1-bc19-f63ce52f417c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='LnkAddItem']/i</value>
      <webElementGuid>416a1f95-9515-42a1-bd7a-6ec76662926f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/a/i</value>
      <webElementGuid>9f17ee0e-2465-4359-9878-47448e207d1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[(text() = 'add' or . = 'add')]</value>
      <webElementGuid>74acc01d-8992-4d26-b0c6-1f5705428783</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
