<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_edit</name>
   <tag></tag>
   <elementGuidId>4dd5db8d-8eab-46b8-9ccf-7e56ab8e584e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#grid_ListData_data_14_4 > div > i.material-icons.md-14.BgPoptiGreen.Color_White.Round_5.Hover</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//i[@onclick='EditEmployeeFloorData(41);']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>9a37282e-c402-4c6b-b9c2-40784b0ec20b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material-icons md-14 BgPoptiGreen Color_White Round_5 Hover</value>
      <webElementGuid>afb892ca-8c5a-4514-93a3-640ef4e6184a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>EditEmployeeFloorData(41);</value>
      <webElementGuid>18aa52df-2127-4b63-baa3-d7fea347172b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>edit</value>
      <webElementGuid>38a80585-3d7e-4260-952b-5748e2ae4a00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;grid_ListData_data_14_4&quot;)/div[1]/i[@class=&quot;material-icons md-14 BgPoptiGreen Color_White Round_5 Hover&quot;]</value>
      <webElementGuid>c42547b5-f660-4bb3-ab23-a8d78a346f43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@onclick='EditEmployeeFloorData(41);']</value>
      <webElementGuid>82f0278d-a32f-440e-a3f4-678b11e02cc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='grid_ListData_data_14_4']/div/i</value>
      <webElementGuid>efc2c0d8-5705-42a5-b997-56efd947a0bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[17]/td[6]/div/i</value>
      <webElementGuid>876d1d26-1e4f-44ec-9a84-d7cb94f045c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[(text() = 'edit' or . = 'edit')]</value>
      <webElementGuid>a2739401-7955-4529-88b7-505eadac06d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
