<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_material-icons md-18 Icon</name>
   <tag></tag>
   <elementGuidId>7253969f-9047-45fe-bc89-43ee85bfed3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.material-icons.md-18.Icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='BtnSave']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>0f704bb3-2597-4830-babe-44650a960693</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material-icons md-18 Icon</value>
      <webElementGuid>e5af1226-5847-4836-9684-c7e98342eeb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BtnSave&quot;)/i[@class=&quot;material-icons md-18 Icon&quot;]</value>
      <webElementGuid>e4147d5f-e4be-4280-9ef5-8e68a20a750c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='BtnSave']/i</value>
      <webElementGuid>06a6b982-b6ab-4cf0-8154-f147d61ee520</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/button/i</value>
      <webElementGuid>d94c449c-126b-4c3b-8f49-c651d5c01099</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
