<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Name</name>
   <tag></tag>
   <elementGuidId>deef7286-3400-49dc-94f9-b2c3505924d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TxtName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TxtName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>43cf1f0b-738a-4718-a82f-c4c9b121a105</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TxtName</value>
      <webElementGuid>d7f279be-b3ba-41e9-baeb-8571d9f4ac79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9742098e-8fc8-4cfc-ad0f-ec3e99748678</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>515a5de0-7a96-48cd-bf29-f776e65d72e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TxtNormalTextBox</value>
      <webElementGuid>a96c0d3e-98f0-492d-a6fd-65b369e25dec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TxtName&quot;)</value>
      <webElementGuid>db8605b4-b395-47fa-a812-01a0dc45935f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TxtName']</value>
      <webElementGuid>f71742b7-26e1-450d-8d2b-cdac6506c986</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='TblEmployeeFloorsInput']/tr/td[2]/input</value>
      <webElementGuid>ab848aa9-92f2-4162-bd48-fae957614ef6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>82b3e853-28ae-4f8e-992a-7d0df12069a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'TxtName' and @type = 'text' and @name = 'Name']</value>
      <webElementGuid>919fc938-dc8c-494d-870a-ea1b9af623c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
