<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_fa-solid fa-bars</name>
   <tag></tag>
   <elementGuidId>ffb7c049-4515-4548-9965-4ea217fd4773</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa-solid.fa-bars</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='katalon_header']/section[3]/div/div/div/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>d7dd9f7b-6c45-4e64-9d2b-3ab3e13b8cd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa-solid fa-bars</value>
      <webElementGuid>80aebfbe-3c14-4eaa-a214-ae50b24c5487</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;katalon_header&quot;)/section[@class=&quot;rebrand_header_mobile undefined&quot;]/div[@class=&quot;wrap_container&quot;]/div[@class=&quot;top_menu&quot;]/div[@class=&quot;katalon_menu_icon&quot;]/i[@class=&quot;fa-solid fa-bars&quot;]</value>
      <webElementGuid>a00699c9-879d-49d2-850e-8c647435ff5e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='katalon_header']/section[3]/div/div/div/i</value>
      <webElementGuid>2b247d4f-1d69-4c89-b877-be85be1ebf81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/i</value>
      <webElementGuid>5ff246ea-a4c1-4c08-a7f5-99a64129086e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
