<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Dresses</name>
   <tag></tag>
   <elementGuidId>8db211a3-1e4e-459c-8129-f2799389bcd0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='desktop-header-cnt']/div[2]/nav/div/div[2]/div/div/div/div/li[2]/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>853f9a09-06fb-43b5-b3c1-0486fa340bf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/dresses?f=Gender%3Amen%20women%2Cwomen</value>
      <webElementGuid>643f5770-4744-4a0f-9d59-9e6c978d6ad8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>desktop-categoryLink</value>
      <webElementGuid>45c044b2-c3f0-4ea1-b744-7618a2e794f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-reactid</name>
      <type>Main</type>
      <value>219</value>
      <webElementGuid>929a5879-015a-4b81-b8e0-950d0dd9b817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dresses</value>
      <webElementGuid>dac8d4dc-d572-4b1b-9b81-d458ab838dcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;desktop-header-cnt&quot;)/div[@class=&quot;desktop-bound&quot;]/nav[@class=&quot;desktop-navbar&quot;]/div[@class=&quot;desktop-navLinks&quot;]/div[@class=&quot;desktop-navContent&quot;]/div[@class=&quot;desktop-navLink&quot;]/div[@class=&quot;desktop-backdropStyle&quot;]/div[@class=&quot;desktop-paneContent&quot;]/div[@class=&quot;desktop-categoryContainer&quot;]/li[@class=&quot;desktop-evenColumnContent desktop-oddColumnContent&quot;]/ul[@class=&quot;desktop-navBlock&quot;]/li[2]/a[@class=&quot;desktop-categoryLink&quot;]</value>
      <webElementGuid>702667ab-197e-47d1-8dbd-01bcbdd1af5b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='desktop-header-cnt']/div[2]/nav/div/div[2]/div/div/div/div/li[2]/ul/li[2]/a</value>
      <webElementGuid>5a360fc2-e23a-4029-b8ce-0da9b55af55b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Dresses')]</value>
      <webElementGuid>39695dd5-8c5a-4682-b3e4-645e8cec4258</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/dresses?f=Gender%3Amen%20women%2Cwomen')]</value>
      <webElementGuid>a58e0f96-a498-4528-a6ab-6a6bb972f7b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/li[2]/ul/li[2]/a</value>
      <webElementGuid>cc746eac-41c5-4a15-8d31-4a02f7f806a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/dresses?f=Gender%3Amen%20women%2Cwomen' and (text() = 'Dresses' or . = 'Dresses')]</value>
      <webElementGuid>6e069f6c-de87-425c-903b-d1902c9cd67e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
