<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_button</name>
   <tag></tag>
   <elementGuidId>2b46ec20-41cd-445e-a3e8-98167f2c4a50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Send to Customer Care']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(2) > input.button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>01054f70-1ef6-4dd7-a24f-6b6375ceb64f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>4f5ab5ad-9223-4d34-9d0f-3727171cb47d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>79f05353-a751-44f7-a4e3-afaeaf6fe549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Send to Customer Care</value>
      <webElementGuid>d3c9a10b-5e61-4a1d-bfc7-f671af4a9ab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contactForm&quot;)/table[@class=&quot;form2&quot;]/tbody[1]/tr[5]/td[2]/input[@class=&quot;button&quot;]</value>
      <webElementGuid>410b9dce-d9d3-4f5b-a745-ad695868b114</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Send to Customer Care']</value>
      <webElementGuid>7c3022d9-8866-4a9e-8e86-165fd0118360</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='contactForm']/table/tbody/tr[5]/td[2]/input</value>
      <webElementGuid>cd7e1756-e709-4406-ba55-d0ee698ec841</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[2]/input</value>
      <webElementGuid>c1463f6a-21f7-42c4-b634-2eeae101087d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>7f0ae407-34dc-4b2a-b0d5-1f42b01294dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
