<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Stop</name>
   <tag></tag>
   <elementGuidId>7395615d-8cfb-43dd-9cdc-81c708d7e319</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='popupInjectionKR']/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#popupInjectionKR > button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2dd80ac8-8dac-47a7-a35d-db0759ed7239</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Stop</value>
      <webElementGuid>60b9ddb0-865b-476c-b798-a7f98e74df03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popupInjectionKR&quot;)/button[1]</value>
      <webElementGuid>580c591a-02ea-47ad-8388-98da52b0f090</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popupInjectionKR']/button</value>
      <webElementGuid>7fd368de-f8c8-4965-b24c-1d4445729631</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Katalon Recorder is recording ...'])[1]/following::button[1]</value>
      <webElementGuid>8bc3db16-20e8-4a07-a92a-3cb77f2bdbe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'popupInjectionKR', '&quot;', ')/button[1]')])[1]/following::button[1]</value>
      <webElementGuid>843e1c64-7bfc-442b-9b24-a87400086c5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Stop']/parent::*</value>
      <webElementGuid>0a8dbd99-e678-4090-a75e-da581b9f06fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/button</value>
      <webElementGuid>eb9a7a8b-7e85-4b5a-a5fe-b081ca07676b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Stop' or . = 'Stop')]</value>
      <webElementGuid>6b921a93-0995-4306-a94d-c83f60c4c634</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
