<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password</name>
   <tag></tag>
   <elementGuidId>6f7d170d-98f3-49bc-963e-3cb547865c45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TxtPassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TxtPassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ecece6fb-6149-492e-8ab1-ef2f9d94f3e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Font Font16 FontBold TxtWithNoBorder Color_Black</value>
      <webElementGuid>01016327-fee3-4415-88b7-5785d962cd9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5f0382f9-3b5a-40cf-a78d-a1d36392f059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>*</value>
      <webElementGuid>082b30f9-e1ec-4f0f-8022-7ed04e1e03c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TxtPassword</value>
      <webElementGuid>e3f90856-256e-4235-94e7-9a6a9a0e4e30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>ad8005bc-12df-4cb3-990f-cb2233e968c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>CallCheckLogin(event);</value>
      <webElementGuid>e6d9766b-fe1c-4928-b9d1-e5ecd28770b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>cefb1606-61d8-429b-a0d5-cb9d4f9efba4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>61424fc2-e11f-4847-a0c7-fe2ff9de1c0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TxtPassword&quot;)</value>
      <webElementGuid>e7f8085d-1eac-4f56-b546-a96a96379af6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TxtPassword']</value>
      <webElementGuid>98231867-e50b-44d9-99a1-147d2cdaa187</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DivPassword']/input</value>
      <webElementGuid>486295a3-ed08-4e71-9d38-148d35cd2d3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>c32bbd4d-1df4-48d1-a766-96ef621c522d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'TxtPassword' and @name = 'Password' and @placeholder = 'Password' and @type = 'password']</value>
      <webElementGuid>0c9aff55-6d07-4c44-9cbf-be007686243b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
