<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_UserId</name>
   <tag></tag>
   <elementGuidId>f2cf0879-3283-47e0-8a71-99a7d0ca4a16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TxtUserId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TxtUserId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b1ee6eeb-f3f2-4bb5-b2da-439e9080bbc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Font Font16 FontBold TxtWithNoBorder Color_Black</value>
      <webElementGuid>7bb32678-78e8-4fd3-9172-e6b1489e0063</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>76b734c4-c71f-4fa7-a756-69d60ce2c226</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>*</value>
      <webElementGuid>11481c41-294c-46ce-8f93-79e3621533d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TxtUserId</value>
      <webElementGuid>7f319ee0-8322-40f9-9ce4-fd95ed6f0d2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UserId</value>
      <webElementGuid>84f14db8-a468-4f28-a63d-bcf3131b7017</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>CallCheckLogin(event);</value>
      <webElementGuid>c953ee2f-4790-4348-8d20-2a8b0bbe9d36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>User Name</value>
      <webElementGuid>bce4527b-dcb2-4417-811c-6d8fe9df4521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d1a0742a-73d7-49d6-bcb7-bfc1b94462a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TxtUserId&quot;)</value>
      <webElementGuid>d5e71439-01b2-4d2d-8f0a-99f187681507</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TxtUserId']</value>
      <webElementGuid>a16ca697-92ab-4982-9cc7-58e4e9f4bd97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DivUserId']/input</value>
      <webElementGuid>4c089ee8-7bbe-4de3-9404-fa5ced4202a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>78f22375-28c3-477c-8fc3-8808cc7b0b09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'TxtUserId' and @name = 'UserId' and @placeholder = 'User Name' and @type = 'text']</value>
      <webElementGuid>8a77578b-7e4d-4771-a480-d85f8526f8a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
