<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Sign In</name>
   <tag></tag>
   <elementGuidId>bc867cc0-d368-4f03-b077-1f55f9dcabd9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.Font15.FontBold</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='BtnSignIn']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1d5a9aa8-1a05-42cf-9277-3d3c0009c688</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Font15 FontBold</value>
      <webElementGuid>7e810830-78e4-4731-8656-e264e0364edd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign In</value>
      <webElementGuid>61a37db9-99c9-4b0d-ad23-b7b732bcdb80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BtnSignIn&quot;)/span[@class=&quot;Font15 FontBold&quot;]</value>
      <webElementGuid>5c5ce1be-9d06-4d44-af43-0453f4a1d31f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='BtnSignIn']/span</value>
      <webElementGuid>4dfbd0b2-d323-4720-990f-8c39b4395a58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span</value>
      <webElementGuid>3fe59c83-d7cc-40b8-8003-133220ee33b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Sign In' or . = 'Sign In')]</value>
      <webElementGuid>816a40e0-2d48-44bf-a772-c9b2025256b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
