<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_button</name>
   <tag></tag>
   <elementGuidId>4312c2f9-8f8a-4830-8739-7e9b1d264c75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Register']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(2) > input.button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c31ba4f8-946f-45b9-8924-9a5bea97db8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>e077b090-4f62-4d61-8a93-02b743c9697d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>06b484fb-5eef-4518-b30f-616669b60053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Register</value>
      <webElementGuid>95b31b45-1777-4b2b-a91e-61247ec6b8cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customerForm&quot;)/table[@class=&quot;form2&quot;]/tbody[1]/tr[13]/td[2]/input[@class=&quot;button&quot;]</value>
      <webElementGuid>602a342a-405e-4b8d-8816-7780f9e81a4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Register']</value>
      <webElementGuid>1a924f2a-4390-4cf2-b9cd-a4fdcdbe7eb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='customerForm']/table/tbody/tr[13]/td[2]/input</value>
      <webElementGuid>be6844d5-fca3-4508-9571-5aab7e94e90a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[13]/td[2]/input</value>
      <webElementGuid>db87171e-ed8d-4c83-bf6c-85343bca8b9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>b84313c7-001b-4849-bbc6-439315d50cb0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
