<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_CONTINUE</name>
   <tag></tag>
   <elementGuidId>9b56a619-eeba-4777-b349-c87ffa721e5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.submitBottomOption</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='reactPageContent']/div/div/div[2]/div[2]/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>46ee8041-894e-4dff-9617-a02081239368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>submitBottomOption</value>
      <webElementGuid>ee79492c-7130-4864-a0cb-a4a5c582e9c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CONTINUE</value>
      <webElementGuid>7640e79b-accb-446a-aea2-5d6bf437dc51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reactPageContent&quot;)/div[@class=&quot;authPage&quot;]/div[1]/div[@class=&quot;signInContainer&quot;]/div[@class=&quot;mobileInputContainer&quot;]/div[@class=&quot;submitBottomOption&quot;]</value>
      <webElementGuid>56d728d2-edc6-418b-9e73-30183178a429</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='reactPageContent']/div/div/div[2]/div[2]/div[3]</value>
      <webElementGuid>a1c3a25b-f8e9-4eb0-9275-a5c34ead5bb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div[2]/div[2]/div[3]</value>
      <webElementGuid>b285ec43-ff62-417f-bc24-6a58d93e3c73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'CONTINUE' or . = 'CONTINUE')]</value>
      <webElementGuid>23e0df5e-80d1-4ac6-bcd8-f2880aa0b063</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
